#
###################################
# Site wide configuration
####################################
#
title: 麦穗时间
email:
description: A simple and awesome blog theme powered by jekyll.
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll", "reading"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/China
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: 麦穗时间
  avatar: leonids-logo.png
  job: "晴子的博客"
  bio: "愿化作火炭上一滴麦芽糖，在翻腾不休的时间里，滋滋地响"
  email:
  disqus-shortname:
  twitter:
  facebook:
  google:
    plus: 
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: lexielee
  gitlab:
  stackoverflow:   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: 
  skype: 
  xing: 
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: 晴子的麦穗时间
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
